### ISSUE TITLE
AutoRole

### ISSUE THREAD

**Issue by Sarmqn** [Sarmqn/Sumi-Chan-Discord-Bot#3]
Auto role does not give the role

**Comment by Sarmqn** [comment]
removed need to be rewritten

**Comment by isigebengu-mikey** [comment]
don't close ths issue if it's still a problem

**Comment by Sarmqn** [comment]
im pretty sure i removed the whole thing @isigebengu-mikey , thats why I closed it, im gonna work on it down the line and im closing issues now cos im adding things to the roadmap in project

**Comment by Sarmqn** [comment]
`await member.add_roles(member, role)` -> `await member.add_roles(role)`.
No need to specify the member object because it's an attribute *of* the member object.
