### ISSUE TITLE
DB + Eco

### ISSUE THREAD

**Issue by Sarmqn** [Sarmqn/Sumi-Chan-Discord-Bot#5]
Not finished making it 

guide = https://replit.com/talk/learn/Discordpy-Discord-Bot-Web-Dashboard-Tutorial/131455

**Comment by Sarmqn** [comment]
Will finish at home due to errors with extracting files from the .zip

**Comment by isigebengu-mikey** [comment]
i can add any functionality needed if someone else does html/css/js

**Comment by isigebengu-mikey** [comment]
here's a cool template

because i'm not going to be adding any styles, i can do the entire website if you guys want
https://github.com/Nouridio/Discord-bot-website-template

**Comment by Sarmqn** [comment]
That really is a nice template thanks, ill sort it out soon

**Comment by Sarmqn** [comment]
too tired for more bs
